<a href="https://colab.research.google.com/github/LeeJeonJin/-GPT--AI-/blob/main/2-Attention-Mechanism.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Query, Key, Value weight 학습
from numpy import array
from numpy import random
from numpy import dot
from scipy.special import softmax

In [2]:
# 네 가지 다른 단어의 인코더 표현
word_1 = array([1, 0, 0])
word_2 = array([0, 1, 0])
word_3 = array([1, 1, 0])
word_4 = array([0, 0, 1])

In [10]:
# 단어 임베딩을 단일 배열로 쌓기(유사도)
words = array([word_1, word_2, word_3, word_4])

In [11]:
words

array([[1, 0, 0],
       [0, 1, 0],
       [1, 1, 0],
       [0, 0, 1]])

In [12]:
# 가중치 행렬 생성
random.seed(42)
W_Q = random.randint(3, size=(3, 3))
W_K = random.randint(3, size=(3, 3))
W_V = random.randint(3, size=(3, 3))

# 쿼리, 키, 값 생성
Q = words @ W_Q
K = words @ W_K
V = words @ W_V

In [13]:
# 모든 주요 벡터에 대해 쿼리 벡터의 점수를 매깁니다.
scores = Q @ K.transpose()

In [14]:
scores

array([[ 8,  2, 10,  2],
       [ 4,  0,  4,  0],
       [12,  2, 14,  2],
       [10,  4, 14,  3]])

In [16]:
# 소프트맥스 연산으로 가중치 계산
weights = softmax(scores / K.shape[1] ** 0.5, axis=1)

# 값 벡터의 가중 합으로 주의를 계산합니다.
attention = weights @ V

In [17]:
print(attention)

[[0.98522025 1.74174051 0.75652026]
 [0.90965265 1.40965265 0.5       ]
 [0.99851226 1.75849334 0.75998108]
 [0.99560386 1.90407309 0.90846923]]


In [18]:
words @ W_Q

array([[2, 0, 2],
       [2, 0, 0],
       [4, 0, 2],
       [2, 1, 2]])